
# Use this docker-compose file to run a PostgreSQL database in a container.
# The database data will be stored in a local directory named 'postgres_data'.

version: '2'
services:
    postgres:
        image: 'postgres:latest'
        restart: always
        volumes:
        - './postgres_data:/var/lib/postgresql/data'
        environment:
        - POSTGRES_PASSWORD=YourPasswordHere
        ports:
        - '5432:5432'